package com.mycompany.todolist;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.text.ParseException;
import java.util.Date;
import java.sql.*;
import javax.swing.ImageIcon;

public class ToDoList extends javax.swing.JFrame {

    /**
     * Creates new form ToDoList
     */
    public ToDoList() {
        initComponents();
        background();
        loadTasksFromDatabase();

        // Start a timer to auto-remove expired tasks every 15 miliseconds
        new javax.swing.Timer(15, e -> {
            autoRemoveExpiredTasks();
        }).start();

        setLocationRelativeTo(null);
        setResizable(false);
        Database.createTable();
    }

    public void background() {
        ImageIcon bgImageResource = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/bg.jpg")));
        Image resource = bgImageResource.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon bg = new ImageIcon(resource);
        jLabel4.setIcon(bg);
    }

    //For date format
    public SimpleDateFormat formatter = new SimpleDateFormat("MMMM dd, yyyy");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnAddTask = new javax.swing.JButton();
        jtxtTaskName = new javax.swing.JTextField();
        jbtnDeleteTask = new javax.swing.JButton();
        jbtnUpdateTask = new javax.swing.JButton();
        jcboxHour = new javax.swing.JComboBox<>();
        jcboxMinutes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcboxAMPM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 77, 135, 35));

        jLabel1.setFont(new java.awt.Font("Migra Extrabold", 0, 36)); // NOI18N
        jLabel1.setText("To-Do List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 14, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Name", "End Date", "End Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(250);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 124, 419, 288));

        jbtnAddTask.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jbtnAddTask.setText("Add Task");
        jbtnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddTaskActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 77, 103, 35));

        jtxtTaskName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jtxtTaskName, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 77, 241, 35));

        jbtnDeleteTask.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jbtnDeleteTask.setText("Delete Task");
        jbtnDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteTaskActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDeleteTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 124, 103, 38));

        jbtnUpdateTask.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jbtnUpdateTask.setText("Update Task");
        jbtnUpdateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateTaskActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdateTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 174, -1, 38));

        jcboxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jcboxHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 276, 52, -1));

        jcboxMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(jcboxMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 276, 52, -1));

        jLabel2.setText(":");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 276, 6, 22));

        jcboxAMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        getContentPane().add(jcboxAMPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 276, 62, -1));

        jLabel3.setText("Set Time:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 254, -1, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 680, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Load Tasks from Database if there's data after exit
    private void loadTasksFromDatabase() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        try (Connection conn = Database.connect(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT name, endDate, endTime FROM tasks")) {
            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getString("name"),
                    rs.getString("endDate"),
                    rs.getString("endTime")
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    //Autoremove Expired Tasks
    private void autoRemoveExpiredTasks() {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        Date now = new Date(); // current date and time

        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) {
            String dateStr = tableModel.getValueAt(i, 1).toString(); // "MMMM dd, yyyy"
            String timeStr = tableModel.getValueAt(i, 2).toString(); // "hh:mm AM/PM"
            try {
                // Combine date and time into a full datetime string
                String datetimeStr = dateStr + " " + timeStr;
                SimpleDateFormat fullFormatter = new SimpleDateFormat("MMMM dd, yyyy hh:mm a");

                Date taskEnd = fullFormatter.parse(datetimeStr);

                // If the current time is after or equal to the task end time
                if (now.compareTo(taskEnd) >= 0) {
                    String taskName = tableModel.getValueAt(i, 0).toString();
                    tableModel.removeRow(i); // Remove from UI

                    // Remove from database
                    try (Connection conn = Database.connect()) {
                        String sql = "DELETE FROM tasks WHERE name = ?";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setString(1, taskName);
                        pstmt.executeUpdate();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Failed to delete expired task from DB: " + e.getMessage());
                    }
                }
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Failed to parse task date/time: " + e.getMessage());
            }
        }
    }

    //After adding, updating, and deleting tasks, autoempty the textboxes
    private void generalAfterSet() {
        jtxtTaskName.setText("");
        jdDate.setDate(null);
        jcboxHour.setSelectedIndex(0);
        jcboxMinutes.setSelectedIndex(0);
    }

    //For getting your desired end time
    public String getSelectedTime() {
        String hour = jcboxHour.getSelectedItem().toString();
        String minute = jcboxMinutes.getSelectedItem().toString();
        String period = jcboxAMPM.getSelectedItem().toString();
        return hour + ":" + minute + " " + period;
    }

    //For checking tasks during add and update tasks
    public boolean checkTasks(boolean isUpdate, int selectedRow) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        String normalizedNewName = jtxtTaskName.getText().replaceAll("\\s+", "");
        String selectedDate = formatter.format(jdDate.getDate());
        String selectedTime = getSelectedTime();

        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (isUpdate && i == selectedRow) {
                continue;
            }

            String existingTaskName = tableModel.getValueAt(i, 0).toString().replaceAll("\\s+", "");
            String existingDate = tableModel.getValueAt(i, 1).toString();
            String existingTime = tableModel.getValueAt(i, 2).toString();

            // Conflict: same name and date, or same time
            boolean sameNameAndDate = normalizedNewName.equalsIgnoreCase(existingTaskName) && selectedDate.equals(existingDate);
            boolean sameTime = selectedTime.equals(existingTime);

            if (sameNameAndDate && sameTime) {
                return true; // Conflict found
            }
        }
        return false; // No conflict
    }

    private void jbtnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddTaskActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            String fullDateTimeStr = formatter.format(jdDate.getDate()) + " " + getSelectedTime();
            SimpleDateFormat fullFormatter = new SimpleDateFormat("MMMM dd, yyyy hh:mm a");
            Date selectedDateTime = null;
            
            if (jtxtTaskName.getText().equals("") || jcboxHour.getSelectedItem().toString().equals("00")) {
                JOptionPane.showMessageDialog(null, "Please enter the required field!");
            } else {
                try {
                    selectedDateTime = fullFormatter.parse(fullDateTimeStr);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Invalid date or time.");
                    return;
                }

                Date now = new Date();
                if (selectedDateTime.before(now)) {
                    JOptionPane.showMessageDialog(null, "The selected date and time has already passed!");
                } else if (checkTasks(false, -1)) {
                    JOptionPane.showMessageDialog(null, "This task is already exists!");
                } else {
                    String[] data = {jtxtTaskName.getText(), formatter.format(jdDate.getDate()), getSelectedTime()};

                    JOptionPane.showMessageDialog(null, "Task added successfully!");
                    tableModel.addRow(data);

                    try (Connection conn = Database.connect()) {
                        String sql = "INSERT INTO tasks(name, endDate, endTime) VALUES(?, ?, ?)";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setString(1, jtxtTaskName.getText());
                        pstmt.setString(2, formatter.format(jdDate.getDate()));
                        pstmt.setString(3, getSelectedTime());
                        pstmt.executeUpdate();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }

                    generalAfterSet();
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Please enter the required field!");
        }
        
    }//GEN-LAST:event_jbtnAddTaskActionPerformed

    private void jbtnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteTaskActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (JOptionPane.showConfirmDialog(null, "Would you delete this task?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (jTable1.getSelectedRowCount() == 1) {
                String taskName = jtxtTaskName.getText();
                JOptionPane.showMessageDialog(null, "Task delete successfully!");
                tableModel.removeRow(jTable1.getSelectedRow());

                try (Connection conn = Database.connect()) {
                    String sql = "DELETE FROM tasks WHERE name = ?";
                    PreparedStatement pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, taskName);
                    pstmt.executeUpdate();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage()); // or show message
                }

                generalAfterSet();
            } else {
                if (jTable1.getModel().getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Table is empty.");
                } else {
                    JOptionPane.showMessageDialog(null, "Please select a single row.");
                }
            }
        }
    }//GEN-LAST:event_jbtnDeleteTaskActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        String tblName = tableModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String tblEndDate = tableModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        jtxtTaskName.setText(tblName);

        try {
            Date date = formatter.parse(tblEndDate);
            jdDate.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        String tblEndTime = tableModel.getValueAt(jTable1.getSelectedRow(), 2).toString().replaceAll("[: ]", "/");
        String splitSectionTime[] = tblEndTime.split("/");
        jcboxHour.setSelectedItem(splitSectionTime[0]);
        jcboxMinutes.setSelectedItem(splitSectionTime[1]);
        jcboxAMPM.setSelectedItem(splitSectionTime[2]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateTaskActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (JOptionPane.showConfirmDialog(null, "Would you update this task?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (jtxtTaskName.getText().equals("") || jdDate.getDate() == null || jcboxHour.getSelectedItem().toString().equals("00")) {
                JOptionPane.showMessageDialog(null, "Please enter the required field!");
            }
            else {
                if (jTable1.getSelectedRowCount() == 1) {
                    String originalName = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                    String name = jtxtTaskName.getText();
                    String date = formatter.format(jdDate.getDate());

                    if (checkTasks(true, jTable1.getSelectedRow())) {
                        JOptionPane.showMessageDialog(null, "This task is still the same!");
                    } else {
                        //set updated value on table row
                        tableModel.setValueAt(name, jTable1.getSelectedRow(), 0);
                        tableModel.setValueAt(date, jTable1.getSelectedRow(), 1);
                        tableModel.setValueAt(getSelectedTime(), jTable1.getSelectedRow(), 2);

                        try (Connection conn = Database.connect()) {
                            String sql = "UPDATE tasks SET name = ?, endDate = ?, endTime = ? WHERE name = ?";
                            PreparedStatement pstmt = conn.prepareStatement(sql);
                            pstmt.setString(1, name);
                            pstmt.setString(2, date);
                            pstmt.setString(3, getSelectedTime());
                            pstmt.setString(4, originalName);
                            pstmt.executeUpdate();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage()); // or show message
                        }

                        JOptionPane.showMessageDialog(null, "Task updated successfully!");
                        generalAfterSet();
                    }
                } else {
                    if (jTable1.getModel().getRowCount() == 0) {
                        JOptionPane.showMessageDialog(null, "Table is empty.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Please select a single row.");
                    }
                }
            }
        }
    }//GEN-LAST:event_jbtnUpdateTaskActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // Check if the click is outside the table
        if (!jTable1.getBounds().contains(evt.getPoint())) {
            jTable1.clearSelection();

            // Optionally clear other fields
            jtxtTaskName.setText("");
            jdDate.setDate(null);
            jcboxHour.setSelectedIndex(0);
            jcboxMinutes.setSelectedIndex(0);
            jcboxAMPM.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDoList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddTask;
    private javax.swing.JButton jbtnDeleteTask;
    private javax.swing.JButton jbtnUpdateTask;
    private javax.swing.JComboBox<String> jcboxAMPM;
    private javax.swing.JComboBox<String> jcboxHour;
    private javax.swing.JComboBox<String> jcboxMinutes;
    private com.toedter.calendar.JDateChooser jdDate;
    private javax.swing.JTextField jtxtTaskName;
    // End of variables declaration//GEN-END:variables

}
